### ISSUE TITLE
Change of wording in readme

### ISSUE THREAD

**Issue by ghost** [iangilman/simple-minecraft-shaders#1]
In the `readme.md` file, at the bottom it says you need to change shaders to see the effect.

I recently found that you can just do `F3 + R` to reload shaders.

**Comment by iangilman** [comment]
Cool! Thank you for letting me know.

I don't see that combo on the list of F3 combos here:

https://minecraft.fandom.com/wiki/Debug_screen#More_debug-keys

Do you know where it comes from? Maybe it's part of the shader mod? Are you using Optifine or something else?

What sort of shaders are you writing, BTW? 😄

**Comment by ghost** [comment]
it is part of the optifine shader documentation

i noticed it whilst trying to create a geometry shader

here is the link [shaders.txt](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/shaders.txt)

**Comment by iangilman** [comment]
Awesome, thank you! I've updated the readme. This is much nicer than having to switch shaders!
