### ISSUE TITLE
Video removed

### ISSUE THREAD

**Issue by myname1111** [iangilman/simple-minecraft-shaders#3]
https://www.youtube.com/watch?v=swjfVnGJiNY this video link which is referenced in the readme got removed, is there any other tutorial for making shaders?  I can't find any!

**Comment by iangilman** [comment]
Bummer! I think they were both from TheCool1James, and their YouTube channel doesn't seem to exist anymore; same with their GitHub. Their Twitter account is still around, so I've hit them up there:

https://twitter.com/iangilman/status/1546326818243809280

But yeah, unfortunately there doesn't seem to be how much in the way of other YouTube tutorials for writing Minecraft shaders! There're tons for just shaders and GLSL in general, if that helps.

If you manage to find some helpful resources, let me know and I can update the readme :-)

Looks like there's a Discord where are a lot of shader writers hang out: the shaderLABs Discord server. You might be able to get some help there:

https://discordapp.com/invite/F4BtNAc

**Comment by myname1111** [comment]
Well that's sad. Just checked out the shaderlab discord and there are lots of resources in the info section. Here's the best one https://github.com/Shadax-stack/MinecraftShaderProgramming/tree/master

**Comment by iangilman** [comment]
@myname1111 That looks like a fantastic tutorial! Thank you for the link. I've added it to the readme and removed the YouTube links:

https://github.com/iangilman/simple-minecraft-shaders/commit/ed64da468137df516dc17b04c416f1f3c495e4d1

Thanks again for alerting me to the issue!
